<div style="border-bottom:3px solid #74171F;padding-bottom:3px; font-weight:bold; font-size:13px; width:200px; color:#9A3023; margin-top:8px;margin-bottom:8px;" align=left>
		<img src="templets/images/ico02.jpg"/>&#160;&#160;[field:title/]
	</div>
	
	<div style=" width:210px; height:140px; margin:0px auto">
		<img width="200" height="128" src="templets/images/zcjs.jpg"/>
		<IMG src="[field:litpic/]" width=220 height=220>
	</div>
	<div style="text-align:left;width:200px;  line-height:22px">　
		[field:description  function='cn_substr(@me,160)'/]...
		<a href="[field:arcurl/]" target="_blank" style="color:#B17500">[查看全文]</a>
	</div>