<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,303);
$z[1][4]['name']="title";
$z[2]=Array("global","",304,330);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",374,404);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",441,468);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",593,624);
$z[5][4]['file']="head.htm";
$z[6]=Array("channel","\r\n<div class=\"vmenu_dolphin\">\r\n<a href='[field:typelink/]'>[field:typename/]</a>\r\n</div>\r\n",1714,1961);
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<div class='vmenu_dolphin'><a href='~typelink~' ~rel~><FONT color=#ff0000>~typename~</FONT></a></div>";
$z[7]=Array("field","",2573,2592);
$z[7][4]['name']="title";
$z[8]=Array("field","",2778,2796);
$z[8][4]['name']="body";
$z[9]=Array("field","",2837,2857);
$z[9][4]['name']="writer";
$z[10]=Array("field","",2891,2947);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("global","",3508,3534);
$z[11][4]['name']="cfg_powerby";

?>