<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,300);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",301,327);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",371,401);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",438,465);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",588,619);
$z[5][4]['file']="head.htm";
$z[6]=Array("channel","\r\n<div class=\"vmenu_dolphin\">\r\n<a href='[field:typelink/]'>[field:typename/]</a>\r\n</div>\r\n",1815,2062);
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<div class='vmenu_dolphin'><a href='~typelink~' ~rel~><FONT color=#ff0000>~typename~</FONT></a></div>";
$z[7]=Array("field","",2674,2697);
$z[7][4]['name']="seotitle";
$z[8]=Array("field","",2896,2917);
$z[8][4]['name']="content";
$z[9]=Array("global","",3482,3508);
$z[9][4]['name']="cfg_powerby";

?>