<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,300);
$z[1][4]['name']="seotitle";
$z[2]=Array("global","",301,327);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",371,401);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",438,465);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",588,619);
$z[5][4]['file']="head.htm";
$z[6]=Array("arclist","\r\n\r\n[field:description /]\r\n\r\n",1204,1276);
$z[6][4]['idlist']="253";
$z[7]=Array("channel","\r\n<div class=\"vmenu_dolphin\">\r\n<a href='[field:typelink/]'>[field:typename/]</a>\r\n</div>\r\n",1791,2038);
$z[7][4]['type']="top";
$z[7][4]['currentstyle']="<div class='vmenu_dolphin'><a href='~typelink~' ~rel~><FONT color=#ff0000>~typename~</FONT></a></div>";
$z[8]=Array("field","",2650,2673);
$z[8][4]['name']="seotitle";
$z[9]=Array("field","",2872,2893);
$z[9][4]['name']="content";
$z[10]=Array("global","",3458,3484);
$z[10][4]['name']="cfg_powerby";

?>