<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,306);
$z[1][4]['name']="typename";
$z[2]=Array("global","",307,333);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",377,407);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",444,471);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("include","",594,625);
$z[5][4]['file']="head.htm";
$z[6]=Array("channel","\r\n<div class=\"vmenu_dolphin\">\r\n<a href='[field:typelink/]'>[field:typename/]</a>\r\n</div>\r\n",1793,2040);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<div class='vmenu_dolphin'><a href='~typelink~' ~rel~><FONT color=#ff0000>~typename~</FONT></a></div>";
$z[7]=Array("field","",2644,2673);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n<li class=\"title\">\r\n<div class=\"title\"><a href='[field:arcurl/]'>[field:title/]</a></div>\r\n<div class=\"time\">[field:pubdate function=\"GetDateMK(@me)\"/]</div>\r\n</li>\r\n",2855,3074);
$z[8][4]['pagesize']="14";
$z[8][4]['titlelen']="60";
$z[9]=Array("pagelist","",3115,3186);
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[10]=Array("global","",3747,3773);
$z[10][4]['name']="cfg_powerby";

?>